version: "3.8"

services: 
  app_db:
    container_name: app_db
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root_pass
    ports:
      - "6033:3306"

  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - app_db
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      PMA_HOST: app_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - app_db
    ports:
      - 8081:80

    